import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "./authcontext";
import { AuthWrapper } from "@/components/shared/AuthComponent/AuthComponents";
import { SidebarProvider } from "@/components/home/sidebar-context";
import { MobileRedirect } from "@/components/shared/MobileRedirect";

const inter = localFont({
  src: [
    {
      path: "../public/font/Inter/Inter-VariableFont_opsz,wght.ttf",
      style: "normal",
    },
    {
      path: "../public/font/Inter/Inter-Italic-VariableFont_opsz,wght.ttf",
      style: "italic",
    },
  ],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Resellstone PC Version",
  description: "Generated by team BGCR",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans antialiased`}>
        <MobileRedirect />
        <AuthProvider>
          <AuthWrapper>
            <SidebarProvider>{children}</SidebarProvider>
          </AuthWrapper>
        </AuthProvider>
        {/* {children} */}
      </body>
    </html>
  );
}
